# Adapted from https://stackoverflow.com/a/64560687/2278742

name: Compile snake

on:
  - push

jobs:
  windows:
    name: run on windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: x86
    - name: compile
      run: | 
        dir
        cl /c /01 /GS- snake.c
        dir
        # https://stackoverflow.com/a/53971921/2278742
        link /nologo /ENTRY:main /NODEFAULTLIB /SUBSYSTEM:WINDOWS snake.obj kernel32.lib user32.lib gdi32.lib ucrt.lib
        dir
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          snake.exe
